version: '2'
services:
  my-dev-box:
    image: openjdk:8
    volumes:
      - /Users/ali/confluent-5.1.0:/confluent
    command: tail -F anything
    environment:
      ZK: zookeeper:2181
      KAFKA: kafka:9092

  zookeeper:
    image: debezium/zookeeper:latest
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    # volumes:
    #   - /Users/ali/projects/ali1dc/legacy-modernization/data/zk:/zookeeper/data

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    ports:
      - "19092:19092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_CLIENT_PORT: 19092
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: rack-a
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    # volumes:
    #   - /Users/ali/projects/ali1dc/legacy-modernization/data/kafka:/kafka/data

  mysql:
    image: debezium/example-mysql:latest
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /Users/ali/projects/ali1dc/legacy-modernization/data/mysql:/var/lib/mysql
    ports:
     -  3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=ali
     - MYSQL_PASSWORD=password
     - MYSQL_DATABASE=order
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080

  postgres:
    image: debezium/postgres:9.6
    hostname: postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    volumes:
      - /Users/ali/projects/ali1dc/legacy-modernization/data/pg:/var/lib/postgresql/data

  connect:
    image: debezium/connect:1.1.1.Final
    ports:
     - 8083:8083
    links:
     - kafka
     - mysql
     - postgres
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
  # elastic:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
  #   ports:
  #    - "9200:9200"
  #   environment:
  #    - http.host=0.0.0.0
  #    - transport.host=127.0.0.1
  #    - xpack.security.enabled=false
 