server.port: 8091
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - health
          - metrics
          - info
          - bindings
  endpoint:
    health.enabled: true
    health.show-details: always

created-by:
  mod: modernized
  legacy: legacy

spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.url: ${PRODUCT_DB_URL}
spring.datasource.username: ${PRODUCT_DB_USER}
spring.datasource.password: ${PRODUCT_DB_PASSWORD}
spring.datasource.test-on-borrow: true
spring.datasource.validation-query: SELECT 1
spring.datasource.log-validation-errors: true
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: none

spring.kafka.bootstrap-servers: ${KAFKA_URL}
spring.cloud.stream.kafka.stream.binder.application-id: product-microservice
spring.cloud.stream.function.definition: categories;products;enrichedProducts;categoryLegacyIds;productLegacyIds
spring.cloud.stream.bindings.categories-in-0.destination: legacy.dbo.categories
spring.cloud.stream.bindings.products-in-0.destination: legacy.dbo.products
spring.cloud.stream.bindings.categoryLegacyIds-in-0.destination: category-legacy-ids
spring.cloud.stream.bindings.productLegacyIds-in-0.destination: product-legacy-ids

spring.cloud.stream.bindings.enrichedProducts-in-0.destination: product.public.products_categories
spring.cloud.stream.bindings.enrichedProducts-in-1.destination: product.public.products
spring.cloud.stream.bindings.enrichedProducts-in-2.destination: product.public.categories
spring.cloud.stream.bindings.enrichedProducts-out-0.destination: enriched-products

spring.cloud.stream.kafka.streams.binder.state-store-retry.max-attempts: 100
spring.cloud.stream.kafka.streams.binder.state-store-retry.backoff-period: 10000
spring.cloud.stream.kafka.bindings.products.consumer.max.poll.interval.ms: 10000

flyway:
  driver-class-name: org.postgresql.Driver
  url: ${PRODUCT_DB_URL}
  user: ${PRODUCT_DB_USER}
  password: ${PRODUCT_DB_PASSWORD}
  enable: true
  test-on-borrow: true
  validation-query: SELECT 1
  log-validation-errors: true


