server.port: 8096
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - health
          - metrics
          - info
          - bindings
  endpoint:
    health.enabled: true
    health.show-details: always

created-by:
  mod: modernized
  legacy: legacy

spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.url: ${SHIPMENT_DB_URL}
spring.datasource.username: ${SHIPMENT_DB_USER}
spring.datasource.password: ${SHIPMENT_DB_PASSWORD}
spring.datasource.test-on-borrow: true
spring.datasource.validation-query: SELECT 1
spring.datasource.log-validation-errors: true
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: none

spring.kafka.bootstrap-servers: ${KAFKA_URL}
spring.cloud.stream.kafka.stream.binder.application-id: shipment-microservice
spring.cloud.stream.kafka.streams.binder.state-store-retry.max-attempts: 100
spring.cloud.stream.kafka.streams.binder.state-store-retry.backoff-period: 10000

spring.cloud.stream.function.definition: shCustomers;shOrders;shipments;legacyShipmentIds;shOrderStatus

spring.cloud.stream.bindings.shCustomers-in-0.destination: enriched-customers
spring.cloud.stream.bindings.shOrders-in-0.destination: order.public.orders
spring.cloud.stream.bindings.shipments-in-0.destination: legacy.dbo.shipping
spring.cloud.stream.bindings.legacyShipmentIds-in-0.destination: shipping-legacy-ids
spring.cloud.stream.bindings.shOrderStatus-in-0.destination: order-status-events

flyway:
  driver-class-name: org.postgresql.Driver
  url: ${SHIPMENT_DB_URL}
  user: ${SHIPMENT_DB_USER}
  password: ${SHIPMENT_DB_PASSWORD}
  enable: true
  test-on-borrow: true
  validation-query: SELECT 1
  log-validation-errors: true

